### ISSUE TITLE
Flipper Zero Multi Board PCB

### ISSUE THREAD

**Issue by arnoakavdb** [IAmOrion/FlipperZeroStuff#1]
Hi, thanks for the board. i order the multitool board to test the power of the flipper but i'm a bit confused with resistor.are they 0 because i can't see any data for them.
Thanks in advance

**Comment by IAmOrion** [comment]
There are 3 resistors on the board, all of which are connected to LEDs.  The value of these resistors will depend entirely on what SMD LEDs you pick.  

Use the datasheet for your chosen LED and fill in the figures on this website to determine the value of the resistor required

https://www.digikey.co.uk/en/resources/conversion-calculators/conversion-calculator-led-series-resistor

**Comment by arnoakavdb** [comment]
ok so if i want to put smd white led is that correct?2Ohm
![image](https://user-images.githubusercontent.com/38015866/214543527-7f37116a-be5f-4e10-a843-d3f941471003.png)

**Comment by IAmOrion** [comment]
a 1000mA LED seems very high - usually white I expect to be around the 60mA mark, but otherwise, yes, if that's what it says go for it.

Realistically you could use a 510ohm, 1k, 10k, etc - it will just reduce the brightness depending on the value.
